<?xml version="1.0" encoding="UTF-8"?>
<definitions>








	<definitions>
	
	<types>
		<schema targetNamespace="http://www.example.org/test/">
			
			
			
		
		</schema>
	</types>
	
	
	</definitions>
	